### ISSUE TITLE
Clearing the date doesn't update altInput

### ISSUE THREAD

**Issue by Abduvakilov** [adrienpoly/stimulus-flatpickr#26]
Manually deleting input doesn't change submitted value
https://glitch.com/edit/#!/relieved-toy?path=public/index.html:29:31
I don't know if it is related to the wrapper or flatpickr itself
Tested on `altInput`, Safari

**Comment by adrienpoly** [comment]
Trying to understand your issue:
From your example 

## scenario 1
1) delete the date form the input field
2) click outside of the field to close the datepicker
3) press the output button

 **Result: the initial date is still outputted**

## scenario 2
1) delete the date form the input field
2) press enter to close the datepicker
3) press the output button

**Result: nothing is outputted**

# Expected behavior 
We should in both case have nothing outputted

I don't think this is related to the wrapper but more the current way of working of flatpickr when using the `allowInput: true` mode.
see this issue which seems related https://github.com/flatpickr/flatpickr/issues/1551

A solution is to listen for the blur event and react to it. I don't think that should be done by the wrapper but more at the Flatpickr level to really fix this. Apparently, there is a consensus that something should be done.

Closing this issue for now. Feel free to reopen it if I didn't understand well
