### ISSUE TITLE
Can't get Flatpickr to display the Rails date value from my database....

### ISSUE THREAD

**Issue by k2director** [adrienpoly/stimulus-flatpickr#62]
Hi! First of all, thanks very much for making Stimulus-Flatpickr, it's very handy to have a Rails-friendly version!

This may seem very basic, but I can't figure out how to make Flatpickr display the date I already have in my database's "due_date" field, when I go to Edit a record. Here's what I'm trying to do, using default_date, but it doesn't display anything: 

Btw, my 'due_date' is a Rails Date field...ie, t.date "due_date"...

`<%= form.text_field :due_date,
      data: {
      controller: "flatpickr",
      flatpickr_default_date: ??????
      flatpickr_alt_format: t("date.formats.long"),
      flatpickr_alt_input: true,
      flatpickr_min_date: Time.zone.now
    }, class:"border" %>
`

For default_date, I've tried: 
   flatpickr_default_date: invoice.due_date
   flatpickr_default_date: :due_date

I'm not sure what else to try. I have used default_date successfully to put today's date in there (flatpickr_default_date: Time.zone.now), but that's the extent of my success. I just can't seem to successfully display an existing value from my database...

Hmmmm, could it be that I need to turn my due_date field into a string field?

Any guidance would be appreciated, thanks!

**Comment by adrienpoly** [comment]
In the Rails app example here is how I pass the date from the backend to Flatpickr
https://github.com/adrienpoly/rails_stimulus_flatpickr/blob/master/app/views/appointments/_datepicker.html.erb

so using the default_date is the way to go 

maybe the problem comes from your field being a Date and not a DateTime. This could explain why Time.zone.now works

looking at the flatpickr doc here are the accepted format for the default date
https://flatpickr.js.org/examples/#supplying-dates-for-flatpickr
so make sure `invoice.due_date` returns one of the accepted format
maybe you can try `invoice.due_date.to_datetime`

**Comment by adrienpoly** [comment]
Closing this for now. 
Feel free to re open it if you still have the issue

**Comment by k2director** [comment]
HI Adrien, I'm sorry for the delay, I had been pulled to another project last week. But I just got back to Flatpickr and YES, you were right about fixing it by converting my Date field to Datetime, like so: 

      flatpickr_default_date: invoice.due_date.to_datetime,

So going forward, I will create my Date fields as Datetimes, for a little more flexibility. 

THANK YOU, I'm really enjoying having such an easy way to handle date picking in a Rails-friendly way...

H
